defaults: &defaults
  source_catalog: "datapact_demo_catalog"
  source_schema: "source_data"
  target_catalog: "datapact_demo_catalog"
  target_schema: "target_data"

validations:
  - task_key: "test_validation_1"
    <<: *defaults
    source_table: "users"
    target_table: "users"
    primary_keys: ["user_id"]
    count_tolerance: 0.01

  - task_key: "test_validation_2"
    <<: *defaults
    source_table: "transactions"
    target_table: "transactions"
    primary_keys: ["transaction_id"]
    count_tolerance: 0.0