# DataPact: Comprehensive Demo Validation Configuration
# This config validates all tables created by the `setup.py` script.
# It is designed to showcase every major feature and edge case.

validations:
  # 1. FAILING TASK: Large table with count, hash, and null discrepancies.
  - task_key: "validate_users_FAIL"
    source_catalog: "datapact_demo_catalog"
    source_schema: "source_data"
    source_table: "users"
    target_catalog: "datapact_demo_catalog"
    target_schema: "target_data"
    target_table: "users"
    primary_keys: ["user_id"]
    count_tolerance: 0.001
    pk_row_hash_check: true
    pk_hash_threshold: 0.05
    null_validation_columns: ["signup_date"]
    null_validation_threshold: 0.01

  # 2. PASSING TASK: Large, identical table.
  - task_key: "validate_transactions_PASS"
    source_catalog: "datapact_demo_catalog"
    source_schema: "source_data"
    source_table: "transactions"
    target_catalog: "datapact_demo_catalog"
    target_schema: "target_data"
    target_table: "transactions"
    primary_keys: ["transaction_id"]
    count_tolerance: 0.0
    pk_row_hash_check: true
    pk_hash_threshold: 0.0

  # 3. ADVANCED: SCD pattern with an accepted threshold of changes.
  - task_key: "validate_products_SCD_PASS"
    source_catalog: "datapact_demo_catalog"
    source_schema: "source_data"
    source_table: "products"
    target_catalog: "datapact_demo_catalog"
    target_schema: "target_data"
    target_table: "products"
    primary_keys: ["product_id"]
    pk_row_hash_check: true
    pk_hash_threshold: 0.025 # Allow for up to 2.5% of rows to change.

  # 4. ADVANCED: Selective column hashing for performance.
  - task_key: "validate_page_views_selective_hash_PASS"
    source_catalog: "datapact_demo_catalog"
    source_schema: "source_data"
    source_table: "page_views"
    target_catalog: "datapact_demo_catalog"
    target_schema: "target_data"
    target_table: "page_views"
    primary_keys: ["session_id"]
    pk_row_hash_check: true
    pk_hash_threshold: 0.0
    # The `view_ts` column is different, but we ignore it in the hash.
    hash_columns: ["user_id", "session_id", "page_path"]

  # 5. EDGE CASE: Table with no primary key. Only count validation will run.
  - task_key: "validate_logs_no_pk_FAIL"
    source_catalog: "datapact_demo_catalog"
    source_schema: "source_data"
    source_table: "log_messages"
    target_catalog: "datapact_demo_catalog"
    target_schema: "target_data"
    target_table: "log_messages"
    count_tolerance: 0.0

  # 6. EDGE CASE: Empty tables. Should pass with zero tolerance.
  - task_key: "validate_empty_tables_PASS"
    source_catalog: "datapact_demo_catalog"
    source_schema: "source_data"
    source_table: "empty_audits"
    target_catalog: "datapact_demo_catalog"
    target_schema: "target_data"
    target_table: "empty_audits"
    count_tolerance: 0.0
