# DataPact Demo Validation Configuration
# This file validates the tables created by the `demo/setup.py` script.
# It is designed to produce one PASS (transactions) and one FAIL (users)
# to demonstrate the tool's reporting capabilities.

validations:
  - task_key: "validate_demo_users_FAIL"
    source_catalog: "datapact_demo_catalog"
    source_schema: "source_data"
    source_table: "users"
    target_catalog: "datapact_demo_catalog"
    target_schema: "target_data"
    target_table: "users"
    primary_keys: ["user_id"]

    # Test 1: Count Validation.
    # Source has 10,000 rows. Target has 10,100. Difference is 1%.
    # This will FAIL because 0.01 > 0.005.
    count_tolerance: 0.005

    # Test 2: Per-Row Hash Validation.
    # 9,800 rows are compared. 500 have different emails. Mismatch is ~5.1%.
    # This will FAIL because 0.051 > 0.05.
    pk_row_hash_check: true
    pk_hash_threshold: 0.05

    # Test 3: Null Count Validation.
    # Source signup_date has 0 nulls. Target has 1000. Difference is infinite.
    # This will FAIL because inf > 0.0.
    null_validation_threshold: 0.0
    null_validation_columns: ["signup_date"]

  - task_key: "validate_demo_transactions_PASS"
    source_catalog: "datapact_demo_catalog"
    source_schema: "source_data"
    source_table: "transactions"
    target_catalog: "datapact_demo_catalog"
    target_schema: "target_data"
    target_table: "transactions"
    primary_keys: ["transaction_id"]

    # These tables are identical, so all tests with zero tolerance will PASS.
    count_tolerance: 0.0
    pk_row_hash_check: true
    pk_hash_threshold: 0.0
