# demo/demo_config.yml

validations:
  - task_key: "validate_demo_users_FAIL"
    source_catalog: "datapact_demo_catalog"
    source_schema: "source_data"
    source_table: "users"
    target_catalog: "datapact_demo_catalog"
    target_schema: "target_data"
    target_table: "users"
    primary_keys: ["user_id"]

    # Test 1: Count Validation (will FAIL)
    # Source: 10,000 | Target: 10,100 (after inserts/deletes)
    count_tolerance: 0.005 # 0.5% tolerance

    # Test 2: Per-Row Hash Validation (will FAIL)
    # ~500 emails updated, causing hash mismatches.
    pk_row_hash_check: true
    pk_hash_threshold: 0.05 # 5% tolerance

    # Test 3: Null Count Validation (will FAIL)
    # ~1000 signup_dates set to NULL in target.
    null_validation_threshold: 0.0
    null_validation_columns: ["signup_date"]

    # Test 4: Aggregate Validation (will PASS)
    # The MAX user_id should be 10300 in the target and 10000 in the source.
    # A high tolerance ensures this passes to demonstrate a passing check.
    agg_validations:
      - column: "user_id"
        validations:
          - { agg: "MAX", tolerance: 0.1 } # 10% tolerance

  - task_key: "validate_demo_transactions_PASS"
    source_catalog: "datapact_demo_catalog"
    source_schema: "source_data"
    source_table: "transactions"
    target_catalog: "datapact_demo_catalog"
    target_schema: "target_data"
    target_table: "transactions"
    primary_keys: ["transaction_id"]

    # These tables are identical, so all tests with zero tolerance will PASS.
    count_tolerance: 0.0
    pk_row_hash_check: true
    pk_hash_threshold: 0.0
    # Add a passing aggregate validation
    agg_validations:
      - column: "amount"
        validations:
          - { agg: "SUM", tolerance: 0.0 }
          - { agg: "AVG", tolerance: 0.0 }
